apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-mongo-db
  labels:
    app: auth-mongo-db
spec:
  serviceName: auth-mongo-service
  replicas: 2
  selector:
    matchLabels:
      app: auth-mongo
  template:
    metadata:
      labels:
        app: auth-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.4
        command: ["mongod"]
        args: ["--config", "/etc/mongo/mongod.conf"]
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
        - name: config-volume
          mountPath: /etc/mongo
      volumes:
      - name: config-volume
        configMap:
          name: auth-mongo-config
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi


  # Look at MongoDB Community Operator