apiVersion: v1
kind: Service
metadata:
  name: auth-mongo-service
  labels:
    app: auth-mongo-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP  # Explicitly specify the protocol
  type: ClusterIP  # Tell kubernetes to use a ClusterIP 
  clusterIP: None  # Tell kubernetes that the clusterip is a headless service
  selector:
    app: auth-mongo
